### PR TITLE
Merged the commits 

### PR DESCRIPTION
**Pull request by Souravirus**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by Souravirus** [comment]
@jywarren Here I have merged the commits, please check it I guess this is the correct way than rebasing

**Comment by jywarren** [comment]
Hmm, if you rebase, you shouldn't see all the commits from upstream -- are you sure you're rebasing your changes over the latest master? Maybe someone from @publiclab/reviewers could help you rebase? 

This may be of some help too but be sure to back up your branch before doing this! 

https://publiclab.org/wiki/contributing-to-public-lab-software#Rewinding+the+master+branch

**Comment by Souravirus** [comment]
Hey I have told a command in https://github.com/jywarren/plots2/pull/263 should I try that?

**Comment by Souravirus** [comment]
I have told what I have done and what commands I have ran in https://github.com/jywarren/plots2/pull/263 . please check it @jywarren

**Pull request closed without merging**
