### PR TITLE
Rebase new

### PR DESCRIPTION
**Pull request by Souravirus**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by Souravirus** [comment]
Hey @jywarren , Please check if I have correctly rebased it.

**Comment by jywarren** [comment]
Hmm, i think rebasing is the way to go but are you sure you're rebasing this over the latest master? Take a look at the workflow I linked to in my comment on https://github.com/jywarren/plots2/pull/264 -- thanks!

**Comment by Souravirus** [comment]
While rebasing, what I did is I fetched the latest commits and let the latest commits be in publiclab/master branch in my local git.
Then from publiclab/master branch I ran this command:
`git rebase jywarren/rails-4.2`
and then cleared all the conflicts in it. 
Then did `git push -f origin rebase_new`. I guess I am correct in this.
Please look at it @jywarren

**Comment by Souravirus** [comment]
Ohh I think I understood what you are telling me to do instead of 
`git rebase jywarren/rails-4.2`
I should have used `git rebase -i jywarren/rails-4.2`
But don't you think that if I have rebased like that then all the commits will be squashed into 1 commit.

**Comment by jywarren** [comment]
Ah -- ok; I think the rebasing is going the opposite way. So what you want to do is:

* enter your local `master` branch, and pull from `publiclab/master` (this should not involve any merges or conflicts if your master has no unique changes that aren't already part of `publiclab/master` -- otherwise you may have to rewind your local master)
* `git pull` from `publiclab/master`
* then check out your feature branch of `rails-4.2`
* back it up with `git branch rails-4.2-bkp`
* then `git rebase master` to detatch your `rails-4.2` branch from it's current position and try to re-attach it to the most recent commit of `publiclab/master`. This will require rebasing and resolving some conflicts.

For more on this, take a look at this tutorial -- it helps explain this visually! 

guidance on rebasing: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

Also: the basic GitHub Flow workflow: https://guides.github.com/introduction/flow/

**Comment by Souravirus** [comment]
I tried to follow the steps you told and has sent a new PR in https://github.com/jywarren/plots2/pull/266 check it if it is OK or not. Thanks!!

**Pull request closed without merging**
