### PR TITLE
rebased by standing at my rails-4.2 branch

### PR DESCRIPTION
**Pull request by Souravirus**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] all tests pass -- `rake test:all`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by Souravirus** [comment]
Hey I did as you told by standing at `jywarren:rails-4.2` branch I rebased it to `publiclab:master` branch. Now is it OK @jywarren

**Comment by jywarren** [comment]
Ah, i think this is good, so now this is where you can finish the 4.2 port, right? @Gauravano how does this look to you?

**Comment by Souravirus** [comment]
Yeah @jywarren I will do rails 4.2 port on it.

**Comment by Gauravano** [comment]
hi @jywarren @Souravirus  , looks good to me

**Comment by Souravirus** [comment]
Hey @jywarren, are we ready to merge this PR. So, that I can start working on rails 4.2 upgrading to rails 4.2 for new commits.

**Comment by jywarren** [comment]
OK!

**Pull request merged**
